name: DP-RPG
version: 1.0.0.4
main: com.darksoldier1404.dpr.DRPG
api-version: 1.15
authors: [ DEAD_POOLIO_ ]
depend:
  - DPP-Core
  - MythicMobs
commands:
  dpra:
    permission: dpr.admin
    description: "DP-RPG Admin Command"
    usage: /dpra
    aliases: [ dpradmin ]
  dprm:
    permission: dpr.admin
    description: "DP-RPG Mob Setting Command"
    usage: /dprm
    aliases: [ dprmob ]
  dstats:
    description: "DP-RPG Stats Command"
    usage: /dstats
    aliases: [ 스텟 ]